# Generated by Django 4.2.6 on 2023-12-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_remove_userinfo_address_remove_userinfo_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressinfo',
            table='user_address_info',
        ),
    ]
