# Generated by Django 4.2.6 on 2023-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_addressinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
