# Generated by Django 4.2.6 on 2023-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_doorlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlock',
            name='door_name',
            field=models.CharField(default='front door', max_length=255),
        ),
    ]
