# Generated by Django 4.2.6 on 2023-12-27 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_doorlock_door_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doorlock',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.addressinfo'),
        ),
    ]
